### ISSUE TITLE
Issue with request body

### ISSUE THREAD

**Issue by arsenx** [satyrius/gcf-koa#1]
Hi Anton, I was working on creating a similar setup until I realized the request body is not being parsed as expected, I looked for answers and ended up on your repo, I was wondering if you've noticed this as well.

Best

**Comment by satyrius** [comment]
Hi! Could you be more specific on the issue please? In meanwhile I can say in that there is not any body-parser middleware configured in my example. Its minimalistic and shows how to plug koa app correctly to the Cloud Functions setup. What happens inside the app is up to a developer.

**Comment by arsenx** [comment]
Yes of course, this works fine for generating the ctx object, but I was simply having trouble manually and with the use of a parser to extract the body's content. I tried running the app with the native listen method and the requests were being parsed as expected. 

I'm assuming it's due to the request format that is given from gcf (express) req and res.

I'll be moving to google cloud run to have a little more control over request handling.

There's no issue in your codebase so i'll close the ticket and was just wondering if you've experienced any similar issues
